name: R Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'install.packages("testthat")'
          Rscript -e 'install.packages("zoo")'
          Rscript -e 'install.packages("lubridate")'
          Rscript -e 'install.packages("readr")'
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'install.packages("cli")'
     
      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'
